package recommend;

import org.json.simple.JSONObject;
import org.json.simple.JSONArray;
import java.util.Random;
import java.util.ArrayList;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import org.springframework.ui.Model;

import hello.User;
import hello.UserRepository;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;	//inject an repository instance

	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String song
			, @RequestParam String artist, @RequestParam String genre) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setSongName(song);
		n.setArtist(artist);
		n.setGenre(genre);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/find") 
	public @ResponseBody String findGenre(@RequestParam String song) {
		//userRepository.findSongExist(song);
		return userRepository.findUserBySong(song).getSongName();
	}

	@RequestMapping(path="/webpage")
    public String webpage(Model model) {
        
        String message;
        JSONObject json = new JSONObject();
        json.put("name", "student");

        JSONArray array = new JSONArray();
        JSONObject item = new JSONObject();
        item.put("information", "test");
        item.put("id", 3);
        item.put("name", "course1");
        array.add(item);

        json.put("course", array);
        message = json.toString();
        
        model.addAttribute("name", message);
        return "index";
    }

    
    @RequestMapping(path="/request")
    public String request(Model model) {
    	
    	//If there is no data in database, we will redirect to index.ftl
        if((int)userRepository.count() == 0) {
            return "index";
        }

        //Retrieve a random song from our database
        int index = (int)(Math.random() * userRepository.count()) + 1;
        String songname = userRepository.findById(index).get().getSongName();
        model.addAttribute("data", songname);

        //Pass random song to spotify api and retrieve an arrayList(3) of recommended songs
        ArrayList<JSONObject> arrList = new ArrayList<JSONObject>(3);

        //This part is test until we have api function to retrieve data
    	JSONObject obj = new JSONObject();
    	obj.put("Book ID", "30");
    	obj.put("Book Name", "asdfasdfa");
    	obj.put("Category", "sdfdddd");
    	obj.put("Price", "125.60");

        JSONObject obj2 = new JSONObject();
        obj2.put("Book ID", "50");
        obj2.put("Book Name", "asdfasdfa");
        obj2.put("Category", "sdfdddd");
        obj2.put("Price", "125.60");

        JSONObject obj3 = new JSONObject();
        obj3.put("Book ID", "80");
        obj3.put("Book Name", "asdfasdfa");
        obj3.put("Category", "sdfdddd");
        obj3.put("Price", "125.60");

        arrList.add(0, obj);
        arrList.add(1, obj2);
        arrList.add(2, obj3);

    	String s = obj.toString();
    	
        //Constructs a string in javascript's array of JSONObject format
        //i.e. [{"id":1,"artist":"Michael Jackson","genre":"Pop","songName":"Billie Jean"},{"id":2,"artist":"Queen","genre":"Rock","songName":"Bohemian Rhapsody"}]
        String arr = "[";
        for(int i = 0; i < arrList.size(); i++) {
            arr += arrList.get(i).toString();
            if(i == arrList.size() - 1) {
                arr+="]";
            } else {
                arr+=",";
            }
        }

        //Pass array of JSONObjects to display.ftl
        model.addAttribute("arrObj", arr);
    	
        //This part delete later        
        model.addAttribute("user", s);
    	

        //Redirect to display.ftl file
        return "display";
    	
    	
    }
    
}